name: Setup Go environment
description: Setup a Go environment and add it to the PATH
author: xsc27
inputs:
  go-version:
    description: The Go version to use. Supports semver spec and ranges.
    required: false
  stable:
    description: Whether to download only stable versions.
    default: 'true'
    required: true
  token:
    description: Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
    required: true
  ssh-private-key:
    description: SSH key to access private repositories.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Go (no version)
      if: ${{ ! inputs.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
        stable: ${{ inputs.stable }}
        token: ${{ inputs.token }}
    - name: Setup Go ${{ inputs.go-version }}
      if: ${{ inputs.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
        stable: ${{ inputs.stable }}
        token: ${{ inputs.token }}
    - name: Get cache paths
      id: cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.cache-paths.outputs.go-build }}
          ${{ steps.cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - if: ${{ inputs.ssh-private-key }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Force git to use SSH
      if: ${{ inputs.ssh-private-key }}
      run: git config --global --add url.'git@github.com:'.insteadOf 'https://github.com/'
      shell: bash
